### ISSUE TITLE
MYSQL ERROR

### ISSUE THREAD

**Issue by shin-vely** [shin-vely/My_APP#3]
MYSQL ERROR -Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary

![오류](https://user-images.githubusercontent.com/77481265/107200264-d50d5400-6a3a-11eb-8979-8a288b5b6fc1.JPG)

**Comment by shin-vely** [comment]
이름변경  : 클래스 변경으로 인해 더 이상 사용하지 않음

![오류수정](https://user-images.githubusercontent.com/77481265/107200814-83b19480-6a3b-11eb-8720-547d805b3d49.JPG)

**Comment by NamWoo** [comment]
나이스 캐취~~~~~!
